HW#32_Django_Advance_Practice/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('products', include("products.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

HW#32_Django_Advance_Practice/main/urls.py
from django.urls import path, include
from .views import home, signup, signin, logout_view, add_to_cart, cart, remove_from_cart, order

urlpatterns = [
    path('', home, name="home"),
    path('signup', signup, name="signup"),
    path('signin', signin, name="signin"),
    path('logout', logout_view, name="logout"),
    path('add-to-cart/<int:id>', add_to_cart, name="add_to_cart"),
    path('cart', cart, name="cart"),
    path('remove-from-cart/<int:id>', remove_from_cart, name="remove_from_cart"),
    path('order', order, name="order")
]

HW#32_Django_Advance_Practice/products/urls.py
from django.urls import path, include
from .views import add_product, product_details, product_by_category, \
    edit_product, delete_product, add_category, category_page

urlpatterns = [
    path('/add', add_product, name="add_product"),
    path('/<int:id>', product_details, name="product_details"),
    path('/category', product_by_category, name="product_by_category"),
    path('/edit/<int:id>', edit_product, name="edit_product"),
    path('/delete/<int:id>', delete_product, name="delete_product"),
    path('/category/add', add_category, name="add_category"),
    path('/category/<str:slug>', category_page, name="category_page")
]

HW#32_Django_Advance_Practice/products/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=100, null=True)
    parent_id = models.IntegerField(null=True)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.IntegerField(null=True, default=0)
    approved_by = models.ForeignKey(User, related_name="approved_by", null=True, on_delete=models.SET_NULL)
    approved = models.BooleanField(default=False)
    display_on_main_page = models.BooleanField(default=False)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.title


class Order(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, null=True)
    email = models.CharField(max_length=255, null=True)
    address = models.CharField(max_length=500, null=True)
    message = models.TextField()
    total_price = models.IntegerField()

    def __str__(self):
        return str(self.id)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.order_id)

HW#32_Django_Advance_Practice/products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    def save(self, commit=True, **kwargs):
        instance = super(ProductForm, self).save(commit=False)
        instance.description = instance.description + "..."
        instance.user = kwargs["user"]
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Product
        fields = ["title", "description", "price", "approved", "display_on_main_page"]

HW#32_Django_Advance_Practice/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from .models import Product, Category
from .forms import ProductForm


def add_product(request):
    if request.user.is_authenticated:
        categories = Category.objects.all()
        if request.method == 'GET':
            form = ProductForm(initial={"user": request.user})
            return render(request, "products/add.html", {"categories": categories, "form": form})
        else:
            form = ProductForm(request.POST)
            if form.is_valid():
                product = form.save(user=request.user, commit=True)
                if product.approved is True:
                    product.approved_by = request.user
                for category in request.POST.getlist('categories[]'):
                    product.categories.add(int(category))
                form.save(user=request.user, commit=True)
                return redirect("/")
            else:
                return render(request, "products/add.html", {"categories": categories, "form": form})
    else:
        return redirect("/")


def product_details(request, id):
    product_in_cart = ""
    product = get_object_or_404(Product, id=id)
    if id in request.session.get("products", []):
        product_in_cart = " IN CART "
    return render(request, "products/details.html", {"product": product, "product_in_cart": product_in_cart})


def product_by_category(request):
    categories = Category.objects.all()
    if request.method == 'GET':
        selected_category = "All"
        products = Product.objects.filter(display_on_main_page=True, approved=True).order_by("title")
        return render(request, "products/category.html",
                      {"categories": categories, "products": products, "selected_category": selected_category})
    else:
        selected_category = int(request.POST.get('categories'))
        products = Product.objects.filter(categories=selected_category, display_on_main_page=True, approved=True)\
            .order_by("title")
    return render(request, "products/category.html",
                  {"categories": categories, "products": products, "selected_category": selected_category})


def edit_product(request, id):
    if request.user.is_authenticated:
        all_categories = Category.objects.all()
        if request.method == 'GET':
            product = get_object_or_404(Product, id=id)
            list_categories = product.categories.filter()
            context = {"product": product, "all_categories": all_categories, "list_categories": list_categories}
            return render(request, "products/edit.html", context)
        else:
            product = get_object_or_404(Product, id=id)
            product.title = request.POST.get('title')
            product.description = request.POST.get('description')
            product.user = request.user
            print("========================================================================")
            print(type(request.POST.get('approved')))
            print(request.POST.get('display_on_main_page'))
            print("========================================================================")
            product.price = request.POST.get('price')
            if request.POST.get('approved') == "on":
                product.approved = True
                product.approved_by = request.user
            else:
                product.approved = False
                product.approved_by = None
            if request.POST.get('display_on_main_page') == "on":
                product.display_on_main_page = True
            else:
                product.display_on_main_page = False
            product.save()
            for category in all_categories:
                if (str(category.id) in request.POST.getlist('categories[]')) \
                        and (category not in product.categories.all()):
                    product.categories.add(category)
                elif (str(category.id) not in request.POST.getlist('categories[]')) \
                        and (category in product.categories.all()):
                    product.categories.remove(category)
                else:
                    pass
            return redirect("/")
    else:
        return redirect("/")


def delete_product(request, id):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, id=id)
        product.delete()
    return redirect("/")


def add_category(request):
    if request.user.is_authenticated:
        categories = Category.objects.order_by("name")
        if request.method == 'POST':
            if request.POST.get("name"):
                category = Category()
                category.user = request.user
                category.name = request.POST.get("name")
                category.slug = request.POST.get("slug")
                category.parent_id = request.POST.get("parent_category")
                category.save()
            return redirect("/")
        else:
            return render(request, "products/category/add.html", {"categories": categories})
    else:
        return redirect("/")


def category_page(request, slug):
    try:
        category = Category.objects.get(slug=slug)
        products = Product.objects.filter(categories=category.id, display_on_main_page=True, approved=True)\
            .order_by("title")
    except Category.DoesNotExist:
        raise Http404()
    return render(request, "products/category/category_page.html", {"category": category.name, "products": products})

HW#32_Django_Advance_Practice/templates/products/add.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h1 class="text-center">Add Product</h1>
        <form method="POST" action="{% url 'add_product' %}">
          {% csrf_token %}
          <div class="mb-3">
              <label for="title" class="form-label">Title</label>
              <input type="text" class="form-control" id="title" name="title" aria-describedby="title">
              {% if form.title.errors %}
                <div class="form-text text-danger">{{ form.title.errors }}</div>
              {% endif %}
          </div>
          <div class="mb-3">
              <label for="description" class="form-label">Description</label>
              <textarea class="form-control" id="description" name="description"></textarea>
              {% if form.description.errors %}
                <div class="form-text text-danger">{{ form.description.errors }}</div>
              {% endif %}
          </div>
          <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="number" min="0" class="form-control" id="price" name="price">
            <input type="checkbox" id="approved" name="approved">
            <label for="approved" style="margin-right:30px">Approved</label>
            <input type="checkbox" id="display_on_main_page" name="display_on_main_page">
            <label for="display_on_main_page">Display on main page</label>
          </div>
          <div class="form-row field-categories">
              <div>
                  <label class="required" for="id_categories">Categories:</label>
                  <div class="related-widget-wrapper">
                      <select multiple name="categories[]" required="" id="id_categories" size="10">
                          {% for category in categories %}
                              <option value="{{ category.id }}">{{ category.name }}</option>
                          {% endfor %}
                      </select>
                  </div>
                  <div class="help">Hold down “Control”, or “Command” on a Mac, to select more than one.</div>
              </div>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

HW#32_Django_Advance_Practice/templates/products/category.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h3 class="text-left">Learning products by category:</h3>
        <form method="POST" action="{% url 'product_by_category' %}">
          {% csrf_token %}
          <div class="form-row field-categories">
              <div>
                  <div class="related-widget-wrapper">
                      <select name="categories" required="" id="id_categories" size="5">
                          {% for category in categories %}
                            {% if selected_category == category.id %}
                              <option selected value="{{ category.id }}">{{ category.name }}</option>
                            {% else %}
                              <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endif %}
                          {% endfor %}
                      </select>
                  </div>
              </div>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
<hr>
<div class="container">
    <div class="row">
        <div class="card-list">
            {% for product in products %}
                <div class="card" style="width: 18rem;">
                  <div class="card-body">
                    <h5 class="card-title">{{ product.title }}</h5>
                    <p class="card-text">{{ product.description|truncatechars:30 }}</p>
                    <a href="{% url 'product_details' id=product.id %}" class="card-link">Details</a>
                  </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

HW#32_Django_Advance_Practice/templates/products/details.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h1 class="text-center">{{ product.title }}</h1>
        <p>{{ product.description }}</p>
        <p class="product-price">Price: {{ product.price }} $</p>
        <hr>
        <a href="#">Created by:     {{ product.user.first_name }} {{ product.user.last_name }}</a>
        <hr>
        <div class="edit_del_btn">
            {% if request.user.is_authenticated and request.user.username == product.user.username %}
                <a type="button" class="btn btn-primary" href="{% url 'edit_product' product.id %}">Edit</a>
                <a type="button" class="btn btn-primary" href="{% url 'delete_product' product.id %}">Delete</a>
            {% endif %}
            {% if product_in_cart %}
                <a type="button" class="btn btn-lg btn-success disabled" href="{% url 'add_to_cart' product.id %}">Buy</a>
            {% else %}
                <a type="button" class="btn btn-lg btn-success" href="{% url 'add_to_cart' product.id %}">Buy</a>
            {% endif %}
            <p style="text-align:center font-weight: bold">{{ product_in_cart }}</p>
        </div>
    </div>
</div>
{% endblock %}

HW#32_Django_Advance_Practice/templates/products/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h1 class="text-center">Edit Product</h1>
        <form method="POST" action="{% url 'edit_product' product.id %}">
          {% csrf_token %}
          <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ product.title }}" aria-describedby="title">
          </div>
          <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea class="form-control" id="description" name="description">{{ product.description }}</textarea>
          </div>
          <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="number" min="0" class="form-control" id="price" name="price" value="{{ product.price }}">
            {% if product.approved %}
                <input type="checkbox" id="approved" name="approved" checked>
            {% else %}
                <input type="checkbox" id="approved" name="approved">
            {% endif %}
            <label for="approved" style="margin-right:30px">Approved</label>
            {% if product.display_on_main_page %}
                <input type="checkbox" id="display_on_main_page" name="display_on_main_page" checked>
            {% else %}
                <input type="checkbox" id="display_on_main_page" name="display_on_main_page">
            {% endif %}
            <label for="display_on_main_page">Display on main page</label>
          </div>
          <div class="form-row field-categories">
              <div>
                  <label class="required" for="id_all_categories">Categories:</label>
                  <div class="related-widget-wrapper">
                      <select multiple name="categories[]" required="" id="id_all_categories" size="10">
                          {% for category in all_categories %}
                            {% if category in list_categories %}
                              <option selected value="{{ category.id }}">{{ category.name }}</option>
                            {% else %}
                              <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endif %}
                          {% endfor %}
                      </select>
                  </div>
                  <div class="help">Hold down “Control”, or “Command” on a Mac, to select more than one.</div>
              </div>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}